# Generated by Django 4.0 on 2021-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Tests', models.IntegerField(max_length=200, null=True)),
                ('ComfirmedCases', models.IntegerField(max_length=200, null=True)),
                ('Recoveries', models.IntegerField(max_length=200, null=True)),
                ('Deaths', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
