# Generated by Django 4.0 on 2021-12-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_coviddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CovidConfirmed', models.IntegerField(null=True)),
                ('CovidRecoveries', models.IntegerField(null=True)),
                ('VaccineFirstDose', models.IntegerField(null=True)),
                ('VaccineFullyVaccinated', models.IntegerField(null=True)),
                ('Deaths', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='ComfirmedCases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='Deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='Recoveries',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='Tests',
            field=models.IntegerField(null=True),
        ),
    ]
