# Generated by Django 4.0 on 2021-12-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_overalldata_alter_coviddata_comfirmedcases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coviddata',
            old_name='ComfirmedCases',
            new_name='ConfirmedCases',
        ),
        migrations.AddField(
            model_name='overalldata',
            name='Active',
            field=models.IntegerField(null=True),
        ),
    ]
