# Generated by Django 4.0 on 2021-12-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_covidconfirmed_overalldata_confirmedcases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overalldata',
            old_name='ConfirmedCases',
            new_name='Confirmed',
        ),
    ]
