# Generated by Django 4.0 on 2021-12-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_confirmedcases_overalldata_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='ConfirmedCases',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='Deaths',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='Recoveries',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='Tests',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='Active',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='Confirmed',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='Deaths',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='FirstDoseVaccinations',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='FullyVaccinated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overalldata',
            name='Recoveries',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
